export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export type UPDATE_CHART_DATA = typeof UPDATE_CHART_DATA;

export const UPDATE_CHART_RANGE = "UPDATE_CHART_RANGE";
export type UPDATE_CHART_RANGE = typeof UPDATE_CHART_RANGE;
