export const UPDATE_STOCK_TICKER = "UPDATE_STOCK_TICKER";
export type UPDATE_STOCK_TICKER = typeof UPDATE_STOCK_TICKER;

export const UPDATE_SELECTED_STOCK = "UPDATE_SELECTED_STOCK";
export type UPDATE_SELECTED_STOCK = typeof UPDATE_SELECTED_STOCK;
