export const UPDATE_SEARCH = "UPDATE_SEARCH";
export type UPDATE_SEARCH = typeof UPDATE_SEARCH;
export const UPDATE_COMPANY_SYMBOLS = "UPDATE_COMPANY_SYMBOLS ";
export type UPDATE_COMPANY_SYMBOLS = typeof UPDATE_COMPANY_SYMBOLS;
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export type UPDATE_SEARCH_QUERY = typeof UPDATE_SEARCH_QUERY;
